import type { PurchaseRow } from './employers'

type BillTo = { company_name?: string | null; business_email?: string | null }

const money = (n: number) =>
  `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

const dateFmt = new Intl.DateTimeFormat('en-US', {
  day: 'numeric',
  month: 'long',
  year: 'numeric',
})

/** Opens a print-ready invoice in a new window; the user saves it as a PDF
 *  from the browser's print dialog ("Save as PDF"). No extra dependency. */
export function downloadInvoice(purchase: PurchaseRow, billTo: BillTo): void {
  const invNo = `INV-${purchase.id.slice(0, 8).toUpperCase()}`
  const date = dateFmt.format(new Date(purchase.created_at))
  const total = money(purchase.amount_usd)

  const html = `<!doctype html><html><head><meta charset="utf-8" />
<title>${invNo}</title>
<style>
  *{box-sizing:border-box} body{font-family:-apple-system,Segoe UI,Arial,sans-serif;color:#0f172a;margin:0;padding:48px;max-width:720px}
  h1{font-size:28px;margin:0}
  .muted{color:#64748b}
  .row{display:flex;justify-content:space-between;gap:24px}
  .box{margin-top:32px;border:1px solid #e2e8f0;border-radius:10px;overflow:hidden}
  table{width:100%;border-collapse:collapse}
  th,td{padding:14px 18px;text-align:left;font-size:14px}
  thead th{background:#f8fafc;color:#64748b;font-weight:600}
  tbody td{border-top:1px solid #e2e8f0}
  tfoot td{border-top:2px solid #e2e8f0;font-weight:700}
  .tag{display:inline-block;padding:2px 10px;border-radius:999px;background:#e7f6ec;color:#0ba02c;font-size:12px;font-weight:600;text-transform:capitalize}
  .pt{margin-top:40px;font-size:12px}
  @media print{body{padding:24px}}
</style></head><body>
  <div class="row">
    <div>
      <h1>Partly Asia</h1>
      <p class="muted">trial.partly.asia</p>
    </div>
    <div style="text-align:right">
      <h2 style="margin:0">Invoice</h2>
      <p class="muted">${invNo}<br/>${date}</p>
    </div>
  </div>

  <div style="margin-top:28px">
    <p class="muted" style="margin:0 0 4px">Billed to</p>
    <strong>${escape(billTo.company_name || 'Customer')}</strong>
    ${billTo.business_email ? `<br/><span class="muted">${escape(billTo.business_email)}</span>` : ''}
  </div>

  <div class="box">
    <table>
      <thead><tr><th>Description</th><th style="text-align:right">Amount</th></tr></thead>
      <tbody>
        <tr>
          <td>${escape(purchase.package)} &mdash; ${purchase.credits} credit${purchase.credits === 1 ? '' : 's'}</td>
          <td style="text-align:right">${total}</td>
        </tr>
      </tbody>
      <tfoot>
        <tr><td>Total (USD)</td><td style="text-align:right">${total}</td></tr>
      </tfoot>
    </table>
  </div>

  <p style="margin-top:20px">Status: <span class="tag">${escape(purchase.status)}</span></p>
  <p class="pt muted">Thank you for your purchase. This invoice was generated by Partly Asia.</p>

  <script>window.onload=function(){window.print()}</script>
</body></html>`

  const w = window.open('', '_blank')
  if (!w) return
  w.document.open()
  w.document.write(html)
  w.document.close()
}

function escape(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}
