import { jsPDF } from 'jspdf'

type BillTo = { company_name?: string | null; business_email?: string | null }

export type InvoiceData = {
  id: string
  /** Line-item text, e.g. "Standard — 3 credits" or "Member — Yearly". */
  description: string
  amount_usd: number
  status: string
  created_at: string
}

const money = (n: number) =>
  `USD ${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

const dateFmt = new Intl.DateTimeFormat('en-US', {
  day: 'numeric',
  month: 'long',
  year: 'numeric',
})

/** Generates a PDF invoice and downloads it as a file (no print dialog). */
export function downloadInvoice(inv: InvoiceData, billTo: BillTo): void {
  const invNo = `INV-${inv.id.slice(0, 8).toUpperCase()}`
  const date = dateFmt.format(new Date(inv.created_at))
  const total = money(inv.amount_usd)

  const doc = new jsPDF({ unit: 'pt', format: 'a4' })
  const M = 56 // left/right margin
  const R = 539 // right edge for right-aligned text (595 - margin)
  let y = 70

  doc.setFont('helvetica', 'bold').setFontSize(22).setTextColor(15, 23, 42)
  doc.text('Partly Asia', M, y)
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(100, 116, 139)
  doc.text('trial.partly.asia', M, y + 16)

  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(15, 23, 42)
  doc.text('INVOICE', R, y, { align: 'right' })
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(100, 116, 139)
  doc.text(invNo, R, y + 16, { align: 'right' })
  doc.text(date, R, y + 30, { align: 'right' })

  y += 70
  doc.setFontSize(10).setTextColor(100, 116, 139)
  doc.text('Billed to', M, y)
  doc.setFont('helvetica', 'bold').setFontSize(12).setTextColor(15, 23, 42)
  doc.text(billTo.company_name || 'Customer', M, y + 16)
  if (billTo.business_email) {
    doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(100, 116, 139)
    doc.text(billTo.business_email, M, y + 32)
  }

  // Table
  y += 70
  doc.setDrawColor(226, 232, 240).setLineWidth(1)
  doc.setFillColor(248, 250, 252)
  doc.rect(M, y, R - M, 26, 'F')
  doc.setFont('helvetica', 'bold').setFontSize(10).setTextColor(100, 116, 139)
  doc.text('DESCRIPTION', M + 12, y + 17)
  doc.text('AMOUNT', R - 12, y + 17, { align: 'right' })

  y += 26
  doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(15, 23, 42)
  doc.text(inv.description, M + 12, y + 20)
  doc.text(total, R - 12, y + 20, { align: 'right' })
  doc.line(M, y + 34, R, y + 34)

  y += 34
  doc.setFont('helvetica', 'bold').setFontSize(11)
  doc.text('Total', M + 12, y + 22)
  doc.text(total, R - 12, y + 22, { align: 'right' })

  y += 60
  doc.setFont('helvetica', 'normal').setFontSize(10).setTextColor(15, 23, 42)
  doc.text(`Status: ${inv.status}`, M, y)

  y += 40
  doc.setFontSize(9).setTextColor(148, 163, 184)
  doc.text(
    'Thank you for your purchase. This invoice was generated by Partly Asia.',
    M,
    y,
  )

  doc.save(`${invNo}.pdf`)
}
