import { Link } from 'react-router-dom'
import { Breadcrumb } from '@/components/app/Breadcrumb'

const LAST_UPDATED = 'September 22, 2026'

type Section = {
  id: string
  num: string
  title: string
  intro?: string
  body: string[]
  bullets?: string[]
}

// Structured the way JobStreet/SEEK, Fiverr and fractional-talent platforms
// lay out their privacy notices: what we collect, why, who we share it with,
// how long we keep it, and what rights you have over it — written around
// what partly.asia actually stores (ID digits, encrypted; contact details,
// exchanged only after a paid unlock; verification documents, never public).
const sections: Section[] = [
  {
    id: 'overview',
    num: '1.',
    title: 'Overview',
    body: [
      'This Privacy Policy explains what personal data partly.asia ("we", "us", "our") collects through the Platform, how we use and share it, and the choices and rights you have. It applies to Businesses, Experts, and visitors to partly.asia.',
      'It should be read together with our ',
    ],
  },
  {
    id: 'collect',
    num: '2.',
    title: 'Information We Collect',
    intro: 'We collect information you give us directly, information generated by using the Platform, and information from third-party services we rely on.',
    body: [],
    bullets: [
      'Account information — name, email address, phone number, password (stored hashed, never in plain text), and for a Business: company name and registration number.',
      'Identity verification (Experts) — the last 4 characters of a recognised local ID document (NRIC/FIN, MyKad, KTP, Thai National ID, or CCCD). These are encrypted before storage using a key that is never stored alongside the data itself, and are never displayed back to you, to any Business, or to any third party, including our own staff.',
      'Verification documents — a copy of an identity document (for the optional Expert Verified Badge) or a business registration document (required for a Business to post). These are stored in a private location, reviewed only by our verification team, and never shown publicly.',
      'Profile & posting content — headline, work experience, categories/skills, portfolio links, LinkedIn URL, resume/CV file, profile photo, and the details of any project a Business posts.',
      'Contact details — the email, phone number, and other contact information a Business or Expert provides, which is only ever shared with a matched counterpart after a Business has released contact and the Expert has paid to unlock it (see "How We Share Information" below).',
      'Payment information — handled directly by Stripe, our payment processor. We receive confirmation that a payment succeeded and limited metadata (amount, currency, country) but never your full card number.',
      'Referral & affiliate data — your referral code, who signed up through your link, and the commissions attributed to you.',
      'Usage & device data — pages visited, actions taken (e.g. applying to a posting), IP address, browser type, and device identifiers, collected automatically through standard web technologies.',
      'Cookies & local storage — used for session management (staying signed in), remembering your language preference, and basic analytics. See Section 8.',
      'Communications — messages you send our support team, and reports you file about another user.',
    ],
  },
  {
    id: 'use',
    num: '3.',
    title: 'How We Use Information',
    intro: 'We use the information above to:',
    body: [],
    bullets: [
      'Create and administer your account, and verify your identity or business registration.',
      'Run the matching algorithm that shortlists Experts for a Posting, and rank Verified Badge holders with priority.',
      'Process payments for a contact Unlock or a Verified Badge, and pay out affiliate commissions.',
      'Send service communications — for example, that a Business released contact to you, that a payment window is closing, or that your Verified Badge is expiring. These are operational messages, not marketing, and cannot be opted out of while you hold an account.',
      'Send optional marketing communications, which you may opt out of at any time.',
      'Investigate reports of misuse, enforce our Terms, and keep the Platform safe.',
      'Improve the Platform — for example, understanding which categories are most requested.',
      'Comply with legal obligations, such as responding to a lawful request from a regulator or law enforcement.',
    ],
  },
  {
    id: 'share',
    num: '4.',
    title: 'How We Share Information',
    body: [
      'We do not sell your personal data.',
    ],
    bullets: [
      'With a matched counterpart — a Business’s full contact details are shared with an Expert, and the Expert’s full contact details are shared with that Business, only after the Business releases contact and the Expert pays to unlock it. Outside of that, a Business sees only a match card (name, headline, experience, verification status) and never an Expert’s contact details, and an Expert never sees a Business’s real name or contact details on a Posting until they unlock it.',
      'With service providers who process data on our behalf under contract, including Stripe (payments), Resend (transactional email), and our cloud hosting/database provider. These providers are only given the data they need to perform their function.',
      'For legal reasons — if required to comply with a law, regulation, legal process, or a lawful request by a public authority.',
      'In a business transfer — if partly.asia is involved in a merger, acquisition, or sale of assets, your information may be transferred as part of that transaction, subject to this Policy or a successor policy of no lesser protection.',
      'With your consent — for any other purpose we describe to you at the time.',
    ],
  },
  {
    id: 'contact-window',
    num: '5.',
    title: 'Contact Exchange & the 5-Day Window',
    body: [
      'When a released contact is unlocked, both parties’ contact details become visible to each other on the Platform for 5 calendar days. After that window, the details are no longer shown on the Platform (though of course either party may have already saved them, since further engagement happens off-platform per our Terms).',
      'For security and privacy, we ask that both sides refer to a lead only through the Platform while a window is open, and never through email forwarding of contact details.',
    ],
  },
  {
    id: 'retention',
    num: '6.',
    title: 'Data Retention',
    body: [
      'We keep your account and profile information for as long as your account is active, and for a reasonable period afterward to comply with legal, accounting, or dispute-resolution obligations.',
      'Uploaded identity documents and business registration documents are automatically deleted 90 days after our team reaches a decision (approved or rejected) — we keep only the decision record (approved/rejected, reviewer, and date), never the file itself, beyond that point. This is a deliberate choice: it limits how much sensitive document data we hold at any given time.',
      'Encrypted identity digits (the last 4 characters of your local ID) are retained for as long as your account is active, since they are how your free basic verification is recorded; they are never displayed to anyone and are deleted when your account is closed.',
      'If you close your account, we delete or anonymise personal data that is no longer needed, other than records we are required to keep (for example, payment records for tax purposes).',
    ],
  },
  {
    id: 'rights',
    num: '7.',
    title: 'Your Rights & Choices',
    intro: 'Depending on where you are, you may have the right to:',
    body: [],
    bullets: [
      'Access the personal data we hold about you.',
      'Correct inaccurate or incomplete data — most profile fields can be edited directly in your dashboard.',
      'Request deletion of your data, including by closing your account from your account settings.',
      'Opt out of the affiliate/referral program at any time.',
      'Opt out of marketing communications via the unsubscribe link in any marketing email.',
      'Object to or restrict certain processing, or request a portable copy of your data, where applicable law provides for this.',
    ],
  },
  {
    id: 'cookies',
    num: '8.',
    title: 'Cookies & Local Storage',
    body: [
      'We use cookies and browser local storage to keep you signed in, remember your language preference, and understand basic usage of the Platform. We do not use cookies for third-party ad targeting. You can control cookies through your browser settings, though some Platform features (such as staying signed in) may not work correctly if you disable them.',
    ],
  },
  {
    id: 'security',
    num: '9.',
    title: 'Data Security',
    body: [
      'We use industry-standard safeguards to protect your information, including encryption of sensitive identity data, private storage for verification documents with access limited to our verification team, and row-level access controls in our database so a user can only see the records they are entitled to see.',
      'No system is perfectly secure, and we cannot guarantee absolute security. If you believe your account has been compromised, contact us immediately.',
    ],
  },
  {
    id: 'transfers',
    num: '10.',
    title: 'International Data Transfers',
    body: [
      'partly.asia serves Businesses globally and Experts based in Singapore, Malaysia, Indonesia, Thailand, Vietnam, and the Philippines. Your data may be processed on servers located outside your own country, including by service providers described in Section 4. Where required, we take steps intended to ensure such transfers are subject to appropriate safeguards.',
    ],
  },
  {
    id: 'children',
    num: '11.',
    title: 'Children’s Privacy',
    body: [
      'The Platform is not directed at, and is not intended for use by, anyone under 18. We do not knowingly collect personal data from children. If you believe a child has provided us with personal data, contact us and we will take steps to delete it.',
    ],
  },
  {
    id: 'changes',
    num: '12.',
    title: 'Changes to This Policy',
    body: [
      'We may update this Privacy Policy from time to time. If we make material changes, we will provide reasonable notice (for example, by email or an in-app notice) before they take effect. The "Last updated" date at the top of this page always reflects the current version.',
    ],
  },
  {
    id: 'contact',
    num: '13.',
    title: 'Contact Us',
    body: [
      'For any privacy question, or to exercise a right described in Section 7, reach our team via the ',
    ],
  },
]

export function PrivacyPage() {
  return (
    <>
      <Breadcrumb
        title="Privacy Policy"
        trail={[{ label: 'Home', to: '/' }, { label: 'Privacy Policy' }]}
      />
      <div className="mx-auto grid w-full max-w-[1320px] gap-12 px-6 py-16 lg:grid-cols-[1fr_260px] lg:px-10">
        <div className="flex flex-col gap-12">
          <div>
            <p className="text-sm text-muted">Last updated: {LAST_UPDATED}</p>
            <p className="mt-3 rounded-md bg-brand-50 px-4 py-3 text-sm leading-6 text-brand-800">
              This draft describes what partly.asia actually collects and how it actually handles that data today.
              It is provided as a starting point for your own legal/privacy counsel to review — for example against
              PDPA (Singapore/Malaysia), GDPR (if you serve EU users), or other local requirements — before it is
              relied on commercially. It is not legal advice.
            </p>
          </div>

          {sections.map((s) => (
            <section key={s.id} id={s.id} className="flex flex-col gap-4 scroll-mt-24">
              <h2 className="text-2xl font-medium text-ink">
                {s.num} {s.title}
              </h2>
              {s.intro && <p className="text-base leading-7 text-muted-600">{s.intro}</p>}
              {s.body.map((p, i) => {
                const isLast = i === s.body.length - 1
                return (
                  <p key={i} className="text-base leading-7 text-muted-600">
                    {p}
                    {isLast && s.id === 'overview' && (
                      <>
                        <Link to="/terms" className="font-medium text-brand hover:underline">
                          Terms &amp; Conditions
                        </Link>
                        , which describe the Platform more broadly.
                      </>
                    )}
                    {isLast && s.id === 'contact' && (
                      <>
                        <Link to="/contact" className="font-medium text-brand hover:underline">
                          Contact page
                        </Link>
                        .
                      </>
                    )}
                  </p>
                )
              })}
              {s.id === 'collect' && (
                <p className="text-sm text-muted-600">
                  See our{' '}
                  <Link to="/trust" className="font-medium text-brand hover:underline">
                    Trust &amp; Verification
                  </Link>{' '}
                  page for how reports about another user are reviewed.
                </p>
              )}
              {s.bullets && s.bullets.length > 0 && (
                <ul className="flex flex-col gap-3">
                  {s.bullets.map((b) => (
                    <li
                      key={b}
                      className="flex gap-3 text-sm text-muted-600 before:mt-2 before:size-1.5 before:shrink-0 before:rounded-full before:bg-muted-slate"
                    >
                      {b}
                    </li>
                  ))}
                </ul>
              )}
            </section>
          ))}

          <p className="text-sm leading-6 text-muted">
            See also our{' '}
            <Link to="/terms" className="font-medium text-brand hover:underline">
              Terms &amp; Conditions
            </Link>{' '}
            for how the Platform, fees, and matching work.
          </p>
        </div>

        <nav className="hidden lg:block">
          <div className="sticky top-6">
            <p className="mb-4 text-xs font-medium uppercase tracking-wide text-muted-400">Table of contents</p>
            <ul className="flex max-h-[calc(100vh-6rem)] flex-col gap-3 overflow-y-auto text-sm">
              {sections.map((s) => (
                <li key={s.id}>
                  <a href={`#${s.id}`} className="text-ink-600 hover:text-brand">
                    {s.num} {s.title}
                  </a>
                </li>
              ))}
            </ul>
          </div>
        </nav>
      </div>
    </>
  )
}
