import { chromium } from 'playwright'
import { createClient } from '@supabase/supabase-js'
import { readFileSync } from 'node:fs'
const env = Object.fromEntries(readFileSync(new URL('./.env.local', import.meta.url),'utf8').split('\n').filter(l=>l.includes('=')).map(l=>l.split('=').map(s=>s.trim())))
const admin = createClient(env.VITE_SUPABASE_URL, env.VITE_SUPABASE_PUBLISHABLE_KEY)
const email=`md2+${Date.now()}@x.com`
const s = await admin.auth.signUp({ email, password:'secret123' })
const { data: emp } = await admin.from('employers').insert({ user_id:s.data.user.id, company_name:'MD2 Co', reg_no:'1', field:[], business_email:email, business_details:'x', looking_for:[] }).select('id').single()
await admin.auth.signOut()
const b = await chromium.launch(); const p = await b.newPage()
const errs=[]; p.on('pageerror',e=>errs.push(e.message))
await p.goto('http://localhost:5173/sign-in',{waitUntil:'networkidle'})
await p.fill('input[type=email]', email); await p.fill('input[type=password]','secret123')
await p.click('button[type=submit]'); await p.waitForURL('**/employer/dashboard',{timeout:12000})
await p.goto('http://localhost:5173/company/register',{waitUntil:'networkidle'}); await p.waitForTimeout(2500)
const ed = p.locator('label:has-text("About us") [contenteditable="true"]')
await ed.click()
// H2 via toolbar
await p.locator('label:has-text("About us") button:has-text("H2")').click()
await p.keyboard.type('Our mission')
await p.keyboard.press('Enter')
await p.keyboard.type('We build tools. ')
// bold via toolbar
await p.locator('label:has-text("About us") button[aria-label="Bold"]').click()
await p.keyboard.type('Reliable ones')
await p.locator('label:has-text("About us") button[aria-label="Bold"]').click()
await p.keyboard.type('.')
await p.keyboard.press('Enter')
await p.locator('label:has-text("About us") button[aria-label="Bullet list"]').click()
await p.keyboard.type('fast')
await p.keyboard.press('Enter')
await p.keyboard.type('simple')
await p.waitForTimeout(300)
await p.locator('button:has-text("Save Changes")').click(); await p.waitForTimeout(1500)
const { data: after } = await admin.from('employers').select('about').eq('id', emp.id).single()
console.log('SAVED MARKDOWN:\n' + after.about)
console.log('\nerrors:', errs.length?errs:'none')
// reload -> editor rehydrates
await p.reload({waitUntil:'networkidle'}); await p.waitForTimeout(2500)
const ed2 = p.locator('label:has-text("About us") [contenteditable="true"]')
console.log('after reload: h2=', await ed2.locator('h2').count(), 'strong=', await ed2.locator('strong').count(), 'li=', await ed2.locator('ul li').count())
await b.close()
await admin.from('employers').delete().eq('id', emp.id)
console.log('cleaned up')
